### ISSUE TITLE
[BUG] Redirect for frontend request.

### ISSUE THREAD

**Issue by FKD13** [SELab-2/OSOC-3#322]
Request from the frontend:
- https://github.com/SELab-2/OSOC-3/blob/4cf6ff7e3a6338c270f210d13512c889f2db6b12/frontend/src/utils/api/users/admins.ts#L11
- https://github.com/SELab-2/OSOC-3/blob/4cf6ff7e3a6338c270f210d13512c889f2db6b12/frontend/src/utils/api/users/admins.ts#L14

Result in a redirect from the backend to `/users/?page=...`

Do we want to use `/users/` or `/users`

**Comment by stijndcl** [comment]
I've also noticed this, not sure if there's anything in the backend that we can change to fix this. It's only for some specific types of requests as well, not all of them. Very strange. I'd say `/users/?` is kinda ugly & the slash should go.
