### ISSUE TITLE
[BUG] [Users] don't add to old edition

### ISSUE THREAD

**Issue by WardM99** [SELab-2/OSOC-3#335]
you can now add a coach to a edition when it's not the latest

**Comment by SeppeM8** [comment]
This might be usefull if you want someone new to see the data from an old edition?

**Comment by stijndcl** [comment]
> This might be usefull if you want someone new to see the data from an old edition?

Old editions are read-only IIRC but you can argue that adding an edition to a list of coaches doesn't modify the edition, but rather the coach, so it doesn't violate the read-only principle. I agree it does have a use-case, it's something we can discuss in the next meeting. I wrote it down.

**Comment by SeppeM8** [comment]
Because adding a coach to and old edition doesn't change data of the edition and it can be usefull to let a coach see a previous edition, we will allow this.
