### ISSUE TITLE
[FEAT] Remove obsolete page titles

### ISSUE THREAD

**Issue by stijndcl** [SELab-2/OSOC-3#358]
- [x] Coaches: #390
- [x] Editions: #391

**Comment by Tiebe-Vercoutter** [comment]
Should the create new edition page get a title just like the create new project page?

**Comment by stijndcl** [comment]
> Should the create new edition page get a title just like the create new project page?

Doesn't hurt I think. Create pages have kept their titles for now so might as well make it consistent.
