### ISSUE TITLE
check edition in dependency

### ISSUE THREAD

**Issue by FKD13** [SELab-2/OSOC-3#372]
This is as an example there are more case this happens: 

the dependency:
```py
def get_student(student_id: int, database: Session = Depends(get_session)) -> Student:
    """Get the student from the database, given the id in the path"""
    return get_student_by_id(database, student_id)
```
returns the student even if it is not a student of the current edition. It would make sense to check this here and not everywhere in the code.

**Comment by stijndcl** [comment]
I think all `/x/:student_id`-endpoints are behind an edition, so you should be able to just add the `get_latest_edition` (not sure what the exact name is, I don't know it by heart) dependency as a parameter to this one & that should do it automatically.
