### ISSUE TITLE
[FEAT] Option to delete a project role

### ISSUE THREAD

**Issue by Tiebe-Vercoutter** [SELab-2/OSOC-3#386]

**Comment by Tiebe-Vercoutter** [comment]
@WardM99 can I get an ETA on this one?

**Comment by WardM99** [comment]
@Tiebe-Vercoutter 1h max 2h

**Comment by Tiebe-Vercoutter** [comment]
@WardM99 can you maybe do #442 while you’re at it? It’s about the same subject.
